### ISSUE TITLE
Running the filter with python3.10 gives IndexError

### ISSUE THREAD

**Issue by isalvadori** [chdemko/pandoc-beamer-block#2]
Hi, 
  I just got a new laptop so I am in the process of re-installing a few things and checking whether everything still works as expected.
I have python3.10 on my machine, and when I try running pandoc with the pandoc-beamer-block filter option I get this error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-beamer-block", line 8, in <module>
    sys.exit(main())
  File "/home/ilenia/.local/lib/python3.10/site-packages/pandoc_beamer_block.py", line 112, in main
    return run_filter(block, doc=doc, prepare=prepare)
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/elements.py", line 1431, in from_json
    return _res_func[tag](c)
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/table_elements.py", line 396, in table_from_json
    ica = decode_ica(c[0])
  File "/home/ilenia/.local/lib/python3.10/site-packages/panflute/utils.py", line 21, in decode_ica
    return {'identifier': lst[0],
IndexError: list index out of range
Error running filter pandoc-beamer-block:
Filter returned error status 1
```

Am I missing something here?
Thanks,
Ilenia

**Comment by chdemko** [comment]
What is the pandoc version used ? (I think panflute is not pandoc 3 compatible)

**Comment by isalvadori** [comment]
I have pandoc 2.9.2.1

**Comment by chdemko** [comment]
At the moment I am too busy with work, I should publish a new version at the end of April.

**Comment by chdemko** [comment]
Fix in new version
